name: pubspec_generator
description: >
  Code generator pubspec.yaml.g.dart from pubspec.yaml.
  Just import `pubspec_generator` and then run `dart run build_runner build`
version: 3.1.0-pre.1
repository: https://github.com/PlugFox/pubspec_generator/tree/master
issue_tracker: https://github.com/PlugFox/pubspec_generator/issues
homepage: https://github.com/PlugFox/pubspec_generator
publish_to: https://pub.dev/
#documentation: https://github.com/PlugFox/pubspec_generator/tree/master
#authors:
#  - Plague Fox <plugfox@gmail.com>
topics:
  - yaml
  - pubspec
  - generator
  - build
  - build_runner
  - codegeneration

screenshots:
  - description: 'Icon'
    path: .img/icon.png

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  analyzer: ^5.12.0
  build: ^2.3.1
  pub_semver: ^2.1.4
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.3.3
  build_runner_core: ^7.2.10
  build_test: ^2.1.5
  test: ^1.21.0