name: pubspec_generator
description: Code generator pubspec.yaml.g.dart from pubspec.yaml
version: 0.0.7
author: Plague Fox <Plugfox@gmail.com>
homepage: https://github.com/plugfox/pubspec_generator

#publish_to: 'none' 

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  build: '>=1.0.0 <2.0.0'
  multiline: '>=1.0.1 <2.0.0'
  yaml: '>=2.2.0 <3.0.0'
  pub_semver: '>=1.4.3 <2.0.0'

dev_dependencies:
  build_test: '>=1.0.0 <2.0.0'
  test: '>=1.0.0 <2.0.0'
