name: pubspec_generator
description: pubspec_generator
version: 0.0.6
author: Plague Fox <Plugfox@gmail.com>
homepage: https://github.com/plugfox/pubspec_generator

#publish_to: 'none' 

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  #meta: '>=1.0.0 <2.0.0'
  build: '>=1.0.0 <2.0.0'
  #analyzer: '>=0.39.8 <1.0.0'
  #build_runner: '>=1.0.0 <2.0.0'
  multiline: '>=1.0.1 <2.0.0'
  yaml: '>=2.2.1 <3.0.0'
  pub_semver: '>=1.4.3 <2.0.0'

dev_dependencies:
  build_test: '>=1.0.0 <2.0.0'
  test: '>=1.0.0 <2.0.0'
