name: pubspec_generator

description: >
  Code generator pubspec.yaml.g.dart from pubspec.yaml.
  Just import `pubspec_generator` and then run `dart run build_runner build`

version: 4.0.0-pre.1

repository: https://github.com/PlugFox/pubspec_generator/tree/master

issue_tracker: https://github.com/PlugFox/pubspec_generator/issues

homepage: https://github.com/PlugFox/pubspec_generator

# publish_to: https://pub.dev/

funding:
  - https://www.buymeacoffee.com/plugfox
  - https://www.patreon.com/plugfox
  - https://boosty.to/plugfox

#documentation: https://github.com/PlugFox/pubspec_generator/tree/master

#authors:
#  - Plague Fox <plugfox@gmail.com>

topics:
  - yaml
  - pubspec
  - generator
  - build
  - build_runner
  - codegeneration

screenshots:
  - description: 'Generated version record'
    path: version.png

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: ^6.0.0
  build: ^2.3.1
  pub_semver: ^2.1.4
  yaml: ^3.1.2

dev_dependencies:
  lints: ^2.0.1
  build_runner: ^2.3.3
  build_runner_core: ^7.2.10
  build_test: ^2.1.5
  test: ^1.21.0