name: pubspec_generator
description: >
  Code generator pubspec.yaml.g.dart from pubspec.yaml
  Just import `pubspec_generator`
  and then run `pub run build_runner build`
version: 2.0.0
repository: https://github.com/PlugFox/pubspec_generator/tree/master
issue_tracker: https://github.com/PlugFox/pubspec_generator/issues
homepage: https://github.com/PlugFox/pubspec_generator
#author: Plague Fox <plugfox@gmail.com>

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  build: '>=1.0.0 <2.0.0'
  yaml: '>=2.2.0 <3.0.0'
  pub_semver: '>=1.4.3 <2.0.0'

dev_dependencies:
  pedantic: '>=1.0.0 <2.0.0'
  build_test: '>=1.0.0 <2.0.0'
  test: '>=1.0.0 <2.0.0'
