name: pubspec_generator
description: >
  Code generator pubspec.yaml.g.dart from pubspec.yaml
  Just import `pubspec_generator`
  and then run `pub run build_runner build`
version: 3.0.0-nullsafety.0
repository: https://github.com/PlugFox/pubspec_generator/tree/master
issue_tracker: https://github.com/PlugFox/pubspec_generator/issues
homepage: https://github.com/PlugFox/pubspec_generator
#author: Plague Fox <plugfox@gmail.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  build: ^2.0.0
  pub_semver: ^2.0.0
  yaml: ^3.0.0

dev_dependencies:
  build_runner: ^1.12.2
  build_runner_core: ^6.0.0
  build_test: ^2.0.0
  test: ^1.16.6
