name: pubspec_generator

description: >
  Code generator pubspec.yaml.g.dart from pubspec.yaml.
  Just import `pubspec_generator` and then run `dart run build_runner build`

version: 4.2.2

repository: https://github.com/PlugFox/pubspec_generator/tree/master

issue_tracker: https://github.com/PlugFox/pubspec_generator/issues

homepage: https://github.com/PlugFox/pubspec_generator

# publish_to: https://pub.dev/

funding:
  - https://www.buymeacoffee.com/plugfox
  - https://www.patreon.com/plugfox
  - https://boosty.to/plugfox

#documentation: https://github.com/PlugFox/pubspec_generator/tree/master

#authors:
#  - Plague Fox <plugfox@gmail.com>

topics:
  - pubspec
  - yaml
  - generator
  - build
  - version

screenshots:
  - description: "Generated version record"
    path: version.png

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

# dart pub global activate --source path .
# dart run pubspec_generator:generate
executables:
  generate: generate
  pubspec_generator: generate

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  build: ^2.3.1
  pub_semver: ^2.1.4
  yaml: ^3.1.2
  args: ^2.7.0
  meta: ^1.16.0
  path: ^1.9.1

dev_dependencies:
  lints: ">=2.0.1 <6.0.0"
  build_runner: ^2.3.3
  build_runner_core: ">=7.2.10 <9.0.0"
  build_test: ^2.1.5
  test: ^1.21.0
