name: pubspec_generator
description: >
  Code generator pubspec.yaml.g.dart from pubspec.yaml.
  Just import `pubspec_generator` and then run `dart run build_runner build`
version: 3.0.1
repository: https://github.com/PlugFox/pubspec_generator/tree/master
issue_tracker: https://github.com/PlugFox/pubspec_generator/issues
homepage: https://github.com/PlugFox/pubspec_generator
publish_to: https://pub.dev/
#documentation: https://github.com/PlugFox/pubspec_generator/tree/master
#authors:
#  - Plague Fox <plugfox@gmail.com>

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  build: ^2.0.0
  pub_semver: ^2.0.0
  yaml: ^3.0.0

dev_dependencies:
  build_runner: '>=1.12.2 <3.0.0'
  build_runner_core: ^7.2.10
  build_test: ^2.0.0
  test: ^1.16.6